M48
; DRILL file {KiCad 5.99.0-unknown-7ef9082c86~117~ubuntu18.04.1} date Thu Mar 11 22:57:28 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-03-11T22:57:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-7ef9082c86~117~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,MechanicalDrill
T1C0.1260
%
G90
G05
T1
; mechanical
X3.9961Y-2.4606
X3.9961Y-3.0512
T0
M30
